### ISSUE TITLE
Recalculate on thread count change causes length error 

### ISSUE THREAD

**Issue by matthewg42** [mwganson/ThreadProfile#24]
Nice addon - very useful!  I found a bug: when the thread count gets updated the Thread Profile object, the length of the resulting object seems to get messed up, and it's necessary to re-create the helix and sweep.

[Video 1: direct thread count value change](https://youtu.be/PtvmFCzNfVc)

[Video 2: indirect thread count change my having a computed thread count, but updating some other property](https://youtu.be/sHQlHYrD4wQ)

**Comment by matthewg42** [comment]
Details of my installation:

![image](https://user-images.githubusercontent.com/654279/105896516-cb352b00-600e-11eb-9830-5c6b7d28fadc.png)
![image](https://user-images.githubusercontent.com/654279/105896820-3d0d7480-600f-11eb-93ea-2e91a04f47d7.png)

**Comment by mwganson** [comment]
Thanks for the report.  Please try with version 1.68 (updated today) and let me know if fixed the issue.

Sorry to be so late in responding.  I didn't get an email notification about this open issue.

**Comment by matthewg42** [comment]
It seems partly fixed... when I change the pitch, the object gets updated properly.  However, thread count now seems to get rounded to a whole number (case from video 2, above).

For example, I might set the Pitch to 2, and then the ThreadCount to =10/Pitch (I want the part to be 10mm long, whatever the Pitch is).  This is fine on initial creation (I guess because 10/2 is an integer), but if I change Pitch to be 3, the length is no longer 10.

**Comment by mwganson** [comment]
Updated to v 1.69.  Please try again.

**Comment by matthewg42** [comment]
Looks good  :)  Thanks!
