### ISSUE TITLE
Bsp or G1/2 thread not avilable

### ISSUE THREAD

**Issue by HARIS4820** [mwganson/ThreadProfile#31]
Plumping threads 1/2 , 3/4, 1 inch thread not aviable

**Comment by mwganson** [comment]
True.  Pipe threads not supported.

**Comment by HARIS4820** [comment]
> True. Pipe threads not supported.

Can we expect it?

**Comment by mwganson** [comment]
No, I don't think I'll be adding pipe threads.  The problem is they're tapered and the way the threadprofile objects work is they're a constant size throughout the sweep.  Tapering the helix doesn't work for this.

**Comment by HARIS4820** [comment]
Thank you for your response

**Comment by crossan007** [comment]
Has anyone found a good way to generate (tapered) pipe threads (such as NPT / MIP)?

**Comment by tomaszn** [comment]
BSP G threads (also called BSPP) are parallel, not tapered.
Would be great to see them included in the presets.
Specifications: https://www.machiningdoctor.com/charts/bsp/#bspp-g
