### ISSUE TITLE
45 degree thread for 3D printing

### ISSUE THREAD

**Issue by thijsdeschildre** [mwganson/ThreadProfile#35]
Is it possible to add a new type of thread, which is like metric but has a 45° angle instead of 60?
For 3D printing, it would make it a LOT easier for parts which you want to screw together. Typically, printers get good results with overhangs up to 45°. Metric is 60°, which doesn't work too well... printed supports take a lot of time to remove, and never look good.
Buttress thread is only 45°, but it's not symmetrical. So you have to print one part upside down, which isn't always possible either.

**Comment by luzpaz** [comment]
Can be closed ?
