### ISSUE TITLE
cannot find ThreadProfile icon

### ISSUE THREAD

**Issue by Patsjemoe** [mwganson/ThreadProfile#48]
Hi,
I installed ThreadProfile 1.82.0, as described, restarted Freecad, but cannot find any toolbar icon to start....
please advise where to find it.
regards
Ludo

**Comment by mwganson** [comment]
You must open the workbench first in order to see the toolbar icons.

**Comment by Patsjemoe** [comment]
Hi Mark,
I managed to see them.
But doing the install by the install button (freecad 0.20) seems not to be
sufficient.
I had to add https://github.com/mwganson/ThreadProfile to the custom
repositories section.. but there is no configure icon......have put it in
the preference packs part, then open it in the workbench, and then open
part design....then it shows up....it seems I have to do that every time.
will test it tomorrow.
thanks for your help
regards
Ludo

**Comment by Patsjemoe** [comment]
Hi,
Thanks for your quick reply.
I assume you mean the part design ?
This is open , but no icons. (see attachment)
Regards
Ludo

**Comment by mwganson** [comment]
I am unable to duplicate the issue.  Right click on the toolbar and ensure the Threadprofile Commands toolbar is not hidden.  You should always provide your full freecad information.  help -> about -> copy to clipboard.  I don't know what your operating system is.  My tests are on windows 10 and ubuntu inside a virtual box vm.
