### ISSUE TITLE
"Do sweep" button is always disabled

### ISSUE THREAD

**Issue by ardugitter** [mwganson/ThreadProfile#62]
In Part design, draw a 15mm diameter circle. Extrude it 12mm.
Go to thread profile workbench. 
Create a new V-thread. Select the M12x1.0 fine profile. Change the pitch to 0.5mm. Set height to 12mm. Set quality to 8,
Click "Make helix" and when asked "Do you want to incorporate this object into PartDesign Body using a wrap feature" select yes.
A 1mm diameter helix is created and not the 12mm expected.
Additionally, the "do sweep" button is disabled.
Do you know what is going wrong? Thank you.

**Comment by mwganson** [comment]
The helix should go into the body automatically, assuming there is an active body and you have the thread profile object selected.  Perhaps there has been some very recent change in FreeCAD. Which version are you using?

The helix diameter is irrelevant with this method of thread creation.

To enable the do sweep button ensure you have both the threadprofile object and the helix object selected in the tree view.

**Comment by ardugitter** [comment]
It worked! I needed to select the correct items in the tree view then the sweep worked perfectly. Thanks!!
